### ISSUE TITLE
Recent slowness on play.rust-lang.org

### ISSUE THREAD

**Issue by mbrubeck** [rust-lang/rust-playpen#230] opened 2016-07-08 21:53 UTC
Sometime around a week ago (I don't know exactly when, sorry) http://play.rust-lang.org/ and playbot got significantly slower than they used to be, and have remained slow since then.  For example, just now a request for https://play.rust-lang.org/evaluate.json with a program that was just `fn main() {}` took 3.8 seconds to return a response.

It seems like it may have gotten even slower in the last day; I've been seeing an increasing number of requests hit the playpen timeout.

**Comment by alexcrichton** [comment] 2016-07-09 01:29
This is likely related to the switch to Docker for containers. Looking at the server now (which is relatively small) I see this in `top`:

```
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND          
   30 root      20   0       0      0      0 R 99.7  0.0   8141:19 kswapd0          
```

I've seen that before but I seem to never have been able to track down *why* it's happening. The docker implementation still takes longer than the original one, but it should be reasonable if the swap daemon isn't thrashing.

**Comment by icanrealizeum** [comment] 2016-07-09 01:51
Can try set `vm.swappiness = 10` via sysctl ? Or something else.

**Comment by alexcrichton** [comment] 2016-07-10 06:49
Unfortunately that didn't quite do it, although it looks very similar to [this bug](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1518457)

**Comment by icanrealizeum** [comment] 2016-07-10 09:13
Hey, thanks for trying it!
I picked a few comments from the bug you linked:
Here's another way to reproduce it: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1518457/comments/109

Here are a few workarounds(that may or may not work):
1. https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1518457/comments/92
2. https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1518457/comments/94
3. https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1518457/comments/96
4. https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1518457/comments/108

Obvious info about kswapd not being about swap exclusively: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1518457/comments/80

**Comment by alexcrichton** [comment] 2016-07-11 17:14
I did the `touch touch /etc/udev/rules.d/40-vm-hotadd.rules` and reboot solution and it appears to be working, after a few days kswapd0 hasn't jumped in cpu usage. I'm gonna close this for now as it looks like it's been taken care of, thanks for the comments everyone and the analysis @icanrealizeum!

**Closed by alexcrichton** 2016-07-11 17:14 UTC
